# IBMPC Options
IBMPC_SECONDARY = no		# enable secondary interface
IBMPC_MOUSE_ENABLE = no   	# enable mouse support
LTO_ENABLE = yes
AUTO_SHIFT_ENABLE = no
LTO_ENABLE = yes
BACKLIGHT_ENABLE = no        # Enable keyboard backlight functionality
MIDI_ENABLE = no             # MIDI controls
AUDIO_ENABLE = no            # Audio output on port C6
UNICODE_ENABLE = no          # Unicode
BLUETOOTH_ENABLE = no        # Enable Bluetooth with the Adafruit EZ-Key HID
RGBLIGHT_ENABLE = no         # Enable WS2812 RGB underlight.
API_SYSEX_ENABLE = no
UNICODEMAP_ENABLE = yes
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no        # Mouse keys
EXTRAKEY_ENABLE = no        # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # Nkey Rollover
